
my:
  greeting: Hello World from Config Server - refreshed thrice
  list:
    values: One, Two, Three, Four, Five


db:
  connection: connection-string-here-from-config-server
  host: 127.0.0.1
  port: 1234
